// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA8VTP2HjV8ypV3QuZ2NxcXGk27cSpuVM',
    appId: '1:441931414033:web:def4ffb92997b7c9148fb0',
    messagingSenderId: '441931414033',
    projectId: 'reporta-ufop',
    authDomain: 'reporta-ufop.firebaseapp.com',
    databaseURL: 'https://reporta-ufop-default-rtdb.firebaseio.com',
    storageBucket: 'reporta-ufop.appspot.com',
    measurementId: 'G-5D0S4V7XBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUzylOctgSMOI_tlt-NwWbMQw1Aw9pBNk',
    appId: '1:441931414033:android:04a181d02a9f7fc8148fb0',
    messagingSenderId: '441931414033',
    projectId: 'reporta-ufop',
    databaseURL: 'https://reporta-ufop-default-rtdb.firebaseio.com',
    storageBucket: 'reporta-ufop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeBwxMZ25-MZor5U-9kqVQ-2X-VdYrNDo',
    appId: '1:441931414033:ios:f263ded7482e1106148fb0',
    messagingSenderId: '441931414033',
    projectId: 'reporta-ufop',
    databaseURL: 'https://reporta-ufop-default-rtdb.firebaseio.com',
    storageBucket: 'reporta-ufop.appspot.com',
    iosBundleId: 'com.example.reportaUfop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeBwxMZ25-MZor5U-9kqVQ-2X-VdYrNDo',
    appId: '1:441931414033:ios:f263ded7482e1106148fb0',
    messagingSenderId: '441931414033',
    projectId: 'reporta-ufop',
    databaseURL: 'https://reporta-ufop-default-rtdb.firebaseio.com',
    storageBucket: 'reporta-ufop.appspot.com',
    iosBundleId: 'com.example.reportaUfop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA8VTP2HjV8ypV3QuZ2NxcXGk27cSpuVM',
    appId: '1:441931414033:web:7ecefc7e30c85dd5148fb0',
    messagingSenderId: '441931414033',
    projectId: 'reporta-ufop',
    authDomain: 'reporta-ufop.firebaseapp.com',
    databaseURL: 'https://reporta-ufop-default-rtdb.firebaseio.com',
    storageBucket: 'reporta-ufop.appspot.com',
    measurementId: 'G-PEMDB7DCNP',
  );
}
